### ISSUE TITLE
Allow PMCs and scavs to play together

### ISSUE THREAD

**Issue by MerijnHendriks** [project-fika/Fika-Plugin#34]
Not sure if possible in live EFT, but it might be cool to allow mixed scavs and pmc groups.

**Comment by Lacyway** [comment]
It does not work in live, but there is nothing stopping us from doing this. I'd want some more input from the community, or simply make it an option in the server config? That way it's not a standard feature but can be enabled for those who wish to.

**Comment by ShieldyArmor** [comment]
_(Omg hiii guys my first comment contribution)_ From a player perspective- Personally don't really see an issue with adding it as an option in the configs. These sort of cool fun-to-haves are always nice to be directly supported in the main project.. Especially if it doesn't end up degrading the performance of anyone not wanting to use said feature.

And with enough of them- can always split it off into a seperate module or mod (mostly saying this in reference to the suggestion about making it possible to hang out in someone's hideout, as well as a potential board game system for that)

**Comment by Lacyway** [comment]
> Totally like the idea. We should just set some boundaries for that, i.e. 2 players start a raid as PMC Client dies Client want to come back as scav in the raid (i.e. I wouldn't allow that for now, it's creating a lot of extra work (see Rejoining match Feature))

Agreed, but this is a WIP from someone and they are getting closer to a working rejoining feature.

> We should also think about "who is the host", just the one wo press host or the PMC? Who defines the "rules of the raid"?
Because ScavRuns differs from PMC runs.
Same thing regarding the Exits - which exits to take?
Also thinking then on the "coop Exits" in woods, Interchange and all the other maps.

If you are a Scav while a PMC is hosting, you would be responsible for your own Scav exfils. The shared ones will still be handled by the host and are set upon joining as it is now. Host in this case is always the one who clicks "Host Raid", they are assigned the host class and own most of the logic in the session.
